name: Rust

on:
  push:
    branches: [ master, bootstrap ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf
          - arm-unknown-linux-gnueabihf
          - x86_64-pc-windows-msvc
    steps:
    - uses: actions/checkout@v2
      
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        target: ${{ matrix.target }}
        override: true
        components: rustfmt, clippy
            
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: false
        command: build
        build: --release --target=${{ matrix.target }} --verbose
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        use-cross: false
        command: test
        build: --release --target=${{ matrix.target }} --verbose
